version: '3.7'
services:
  ghidra-server:
    image: v0lp3/ghidra-server:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - P1
        - P2
        - P3
    container_name: ghidra-server
    ports:
      - 13100
      - 13101
      - 13102
    volumes:
      - "/opt/ghidra/repositories:/opt/ghidra/repositories"
    restart: unless-stopped
