---
- name: Remove docker older versions
  apt:
    name: "{{item}}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install some required packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Update apt and install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes

  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Configure the current user to use docker without sudo privileges
  include_tasks: post-installation.yml
